version: "3"

services:
  nginx:
    image: nginx
    labels:
      - docker.nginx
    volumes:
      - ${LOCAL_CODE_PATH}:/opt/www/ #本地项目目录映射到nginx容器目录（如果nginx中try_files就必须映射）
      - ./nginx/vhost:/etc/nginx/vhost
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "8080:8080"
    restart: unless-stopped

  php8:
    build:
      context: ./php8/
    volumes:
      - ${LOCAL_CODE_PATH}:/opt/www/ #本地项目目录映射到php容器目录（必须映射）
    extra_hosts:            # 设置容器 hosts
      - "local.erp.com:192.168.31.136"
    ports:
      - "9501:9501"
      - "9502:9502"
      - "9503:9503"
    stdin_open: true
    tty: true
    restart: unless-stopped

  php:
    build:
      context: ./php/
      args:
        PHP_VERSION: ${PHP_VERSION}
        NPM_VERSION: ${NPM_VERSION}
    volumes:
      - ${LOCAL_CODE_PATH}:/opt/www/ #本地项目目录映射到php容器目录（必须映射）
      #- ./php/php.ini:/usr/local/etc/php/php.ini
    extra_hosts:            # 设置容器 hosts
      - "oss-cn-shenzhen.aliyuncs.com:120.77.166.198"
    stdin_open: true
    tty: true
    restart: unless-stopped

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWD}
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/data8:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    restart: unless-stopped

  redis-db:
    image: redis
    volumes:
      - ./redis/db_data:/data
    ports:
      - "${REDIS_DB_PORT}:6379"
    command: redis-server --requirepass "${REDIS_PASSWD}" --appendonly yes #设置密码， 持久化到磁盘
    restart: unless-stopped

  redis-cache:
    image: redis
    ports:
      - "${REDIS_CACHE_PORT}:6379"
    command: redis-server --requirepass "${REDIS_PASSWD}" #设置密码
    restart: unless-stopped
  nacos:
    image: nacos/nacos-server:v2.2.3
    environment:
      MODE: standalone
      NACOS_SERVER_IP: 127.0.0.1
      NACOS_AUTH_ENABLE: true
      NACOS_AUTH_USER_AGENT_AUTH_WHITE_ENABLE: false
      NACOS_AUTH_IDENTITY_KEY: nacos
      NACOS_AUTH_IDENTITY_VALUE: nacos
      NACOS_AUTH_TOKEN: VGhpc0lzTXlDdXN0b21TZWNyZXRLZXkwMTIzNDU2Nzg=
    volumes:
      - ./nacos/logs/:/home/nacos/logs
      - ./nacos/data/:/home/nacos/data/
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    restart: unless-stopped
  kafka:
    image: bitnami/kafka:latest
    ports:
      - '9092:9092'
    volumes:
      - ./kafka/data:/bitnami/kafka
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.102.74:9092
#  es:
#    image: elasticsearch:8.8.0
#    environment:
#      - node.name = es01
#      - discovery.type=single-node
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - ELASTIC_PASSWORD=123456 # password for user: elastic
#      - KIBANA_PASSWORD=tQfGMtENk7DVhPnf-xm4 # password for user: kibana_system
#    volumes:
#      - ./elasticsearch/data:/usr/share/elasticsearch/data
#      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
#      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
#    ports:
#      - "9200:9200"
#    restart: unless-stopped
#  es-head:
#    image: mobz/elasticsearch-head:5
#    volumes:
#      - ./elasticsearch/vendor.js:/usr/src/app/_site/vendor.js
#    ports:
#      - "9100:9100"
#    restart: always
#  kibana:
#    image: kibana:8.8.0
#    volumes:
#      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
#    ports:
#      - "5601:5601"
#    restart: always
#  logstash:
#    image: logstash:8.8.0
#    volumes:
#      - ${LOCAL_CODE_PATH}/precision_solution/log/:/var/log/solution/
#      - ${LOCAL_CODE_PATH}/sumian-shell/runtime/logs:/var/log/sumian-shell/
#      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
#      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
#    ports:
#      - "5405:5405"
#    restart: always
  jenkins:
    image: jenkins/jenkins:2.401.2-lts
    ports:
      - "8890:8080"
      - "8891:50000"
    volumes: # 卷挂载路径
      - ./jenkins/home:/var/jenkins_home  # 这是我们一开始创建的目录挂载到容器内的jenkins_home目录
#  supervisor:
#      build: ./supervisor
#      volumes:
#        - ${LOCAL_CODE_PATH}:/opt/www/
#        - ./supervisor/conf.d:/etc/supervisor/conf.d
#        - ./supervisor/cron.d:/etc/cron.d
#      depends_on:
#        - php
#      restart: unless-stopped
